#!/bin/bash

###Localization (replace accordingly to your Timezone):

ln -sf /usr/share/zoneinfo/America/New_York /etc/localtime
hwclock --systohc
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
echo 'LANG="en_US.UTF-8"' > /etc/locale.conf

###Hostname and Hosts file:

echo "Arch.localdomain" > /etc/hostname
cat <<EOF> /etc/hosts
127.0.0.1	 localhost
::1		 localhost
127.0.1.1	 Arch.localdomain		Arch
EOF

###Modify mkinitcpio.conf to add and btrfs:
		
vim /etc/mkinitcpio.conf

###HOOKS=(base systemd autodetect modconf block keyboard sd-vconsole filesystems shutdown)###

###Exeucte mkinitcpio

mkinitcpio -p linux-lts

###systemd-boot install:

bootctl install

###Edit the loader.conf file in the /boot/loader directory:

cat <<EOF> /boot/loader/loader.conf
timeout 3
#console-mode keep
default arch-*
editor no
EOF

###Copy the arch.conf file to the  entries directory:
	
cp /usr/share/systemd/bootctl/arch.conf /boot/loader/entries/

###Edit the details for the arch.conf file:

cat <<EOF> /boot/loader/entries/arch.conf
title Arch Linux
linux /vmlinuz-linux-lts
initrd /initramfs-linux-lts.img
options root=LABEL=archroot rw
EOF

###Update bootloader
	
bootctl update

###Root password:

passwd

echo "Enter new user name:"
read user

useradd -m -G users,wheel,audio -s /bin/bash $user
passwd $user

chmod 0755 /etc
chmod -R 755 /var/lib/pacman

pacman -Sd xf86-input-libinput xorg-xinit xorg-server xorg-xsetroot firefox neofetch git alsa-utils sxiv nitrogen maim dmenu sudo fakeroot make gcc patch freetype2 pkg-config

echo "Uncomment wheel is sudo. Press enter to continue."
read continue

visudo

cd /opt
git clone https://aur.archlinux.org/yay-git.git
chown -R $user:$user ./yay-git


echo "cd into /opt/yay-git"
echo " Type *makepkg -si* then *yay -Syu* and *yay -S st dwm* "

###To remove a package using yay use the command.
# yay -Rns package_name

###To clean up all unwanted dependencies on your system, issue the command.
# yay -Yc

su $user

echo "exec dwm" > ~/.xinitrc
echo "startx" >> ~/.bash_profile

systemctl enable NetworkManager
